/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 15ec82ee65aaa72dbc3c1770f4f2314b)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	EMAIL_FROM: string;
	TURNSTILE_SITE_KEY: string;
	RANKED_ENABLED: string;
	MAX_RUN_BYTES: string;
	MAX_RUN_SECONDS: string;
	MONTHLY_BYTE_BUDGET: string;
	DAILY_USER_BYTE_BUDGET: string;
	DAILY_EMAIL_BUDGET: string;
	UPSTREAM_CONCURRENCY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "EMAIL_FROM" | "TURNSTILE_SITE_KEY" | "RANKED_ENABLED" | "MAX_RUN_BYTES" | "MAX_RUN_SECONDS" | "MONTHLY_BYTE_BUDGET" | "DAILY_USER_BYTE_BUDGET" | "DAILY_EMAIL_BUDGET" | "UPSTREAM_CONCURRENCY">> {}
}
